package com.fajrbahr.mediatork.ksp.koin

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.Modifier

class MediatorKKoinProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    private var processed = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (processed) return emptyList()
        processed = true

        val requestHandlers = resolver.findConcreteImplementations("RequestHandler")
        val notificationHandlers = resolver.findConcreteImplementations("NotificationHandler")

        if (requestHandlers.isEmpty() && notificationHandlers.isEmpty()) {
            logger.info("MediatorK Koin KSP: no handlers found")
            return emptyList()
        }

        logger.info("MediatorK Koin KSP: found ${requestHandlers.size} request handlers, ${notificationHandlers.size} notification handlers")

        generateKoinModule(requestHandlers, notificationHandlers)

        return emptyList()
    }

    private fun Resolver.findConcreteImplementations(interfaceName: String): List<KSClassDeclaration> =
        getAllFiles()
            .filter { file -> !isTestFile(file.filePath) }
            .flatMap { it.declarations }
            .filterIsInstance<KSClassDeclaration>()
            .filter { cls ->
                !cls.modifiers.contains(Modifier.ABSTRACT) &&
                !cls.modifiers.contains(Modifier.SEALED) &&
                cls.classKind.name == "CLASS" &&
                cls.superTypes.any { it.resolve().declaration.simpleName.asString() == interfaceName }
            }
            .toList()

    private fun isTestFile(path: String): Boolean =
        path.contains("/test/") || path.contains("Test.kt") || path.contains("Spec.kt")

    private fun generateKoinModule(
        requestHandlers: List<KSClassDeclaration>,
        notificationHandlers: List<KSClassDeclaration>,
    ) {
        val allHandlers = requestHandlers + notificationHandlers
        val allFiles = allHandlers.mapNotNull { it.containingFile }.toTypedArray()

        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = true, *allFiles),
            packageName = "com.fajrbahr.mediatork.generated",
            fileName = "GeneratedKoinMediatorModule",
        )

        file.bufferedWriter().use { writer ->
            writer.write(buildString {
                appendLine("package com.fajrbahr.mediatork.generated")
                appendLine()
                appendLine("// Auto-generated by mediatork-ksp-koin. Do not edit.")
                appendLine()
                appendLine("import com.fajrbahr.mediatork.HandlerRegistry")
                appendLine("import com.fajrbahr.mediatork.MediatorRegistrar")
                appendLine("import org.koin.core.module.dsl.singleOf")
                appendLine("import org.koin.dsl.bind")
                appendLine("import org.koin.dsl.module")

                val imports = allHandlers
                    .map { "${it.packageName.asString()}.${it.simpleName.asString()}" }
                    .distinct()
                    .sorted()
                imports.forEach { appendLine("import $it") }

                appendLine()

                appendLine("class GeneratedMediatorRegistrar(")
                allHandlers.forEachIndexed { i, handler ->
                    val name = handler.simpleName.asString()
                    val prop = name.replaceFirstChar { it.lowercaseChar() }
                    val comma = if (i < allHandlers.lastIndex) "," else ""
                    appendLine("    private val $prop: $name$comma")
                }
                appendLine(") : MediatorRegistrar {")
                appendLine("    override fun register(registry: HandlerRegistry) {")
                appendLine("        registry.scope {")
                allHandlers.forEach { handler ->
                    val prop = handler.simpleName.asString().replaceFirstChar { it.lowercaseChar() }
                    appendLine("            +$prop")
                }
                appendLine("        }")
                appendLine("    }")
                appendLine("}")
                appendLine()

                appendLine("val generatedHandlersModule = module {")
                allHandlers.forEach { handler ->
                    appendLine("    singleOf(::${handler.simpleName.asString()})")
                }
                appendLine("    singleOf(::GeneratedMediatorRegistrar) bind MediatorRegistrar::class")
                appendLine("}")
            })
        }
    }
}
